services:
  magic-workspace:
    image: mageai/mageai:latest
    command: mage start capstone_project
    env_file:
      - .env
    environment:
      USER_CODE_PATH: /home/src/capstone_project
    ports:
      - "6789:6789"
    volumes:
      - ../:/home/src/
    restart: on-failure:5
    networks:
      - shared_grid

# Define the external bridge to your live data environment
networks:
  shared_grid:
    external: true
    name: kafka-streaming_default